# Generated by Django 4.1.6 on 2023-02-16 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spendings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='spendings',
            options={'verbose_name': 'spending', 'verbose_name_plural': 'spendings'},
        ),
    ]
