# Generated by Django 4.1.6 on 2023-02-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendings', '0002_alter_categories_options_alter_spendings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendings',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
