# Generated by Django 4.1.6 on 2023-02-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendings', '0003_alter_spendings_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spendings',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
